version: '3.3'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postrges_dbdate:/var/lib/postgres/data/
    env_file:
      - ./.env

  web:
    image: pashtet777/fgback:v2.13
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    depends_on:
      - db
    env_file:
      - ./.env

  frontend:
    image: pashtet777/fgfront:v2.13
    volumes:
      - ../frontend/:/app/result_build/

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
    depends_on:
      - frontend

volumes:
  postrges_dbdate:
  static_value:
  media_value: