# Generated by Django 3.2.16 on 2023-01-12 14:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-zА-Яа-яЁё\\s]+$', message='The tag name can only contain letters and spaces')], verbose_name='tag name')),
                ('color', models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator('#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{6})$', message='A hex triplet is a six-digit, three-byte hexadecimal number. EXAMPLE --> #FF0000')], verbose_name='HEX tag color')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='link')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-id'],
            },
        ),
    ]
