# Generated by Django 3.2.16 on 2022-12-17 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True, verbose_name='tag name')),
                ('color', models.CharField(max_length=10, unique=True, verbose_name='tag color')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='link')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['-id'],
            },
        ),
    ]
