# Generated by Django 3.2.16 on 2022-12-23 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_alter_tag_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(choices=[('#FF0000', 'RED'), ('#FF8000', 'ORANGE'), ('#FFFF00', 'YELLOW'), ('#80FF00', 'GREEN'), ('#00FFFF', 'LIGHT_BLUE'), ('#0080FF', 'BLUE'), ('#7F00FF', 'EPIC'), ('#FF00FF', 'PINK'), ('#FF007F', 'CORAL')], max_length=7, unique=True, verbose_name='HEX tag color'),
        ),
    ]
